# Generated by Django 3.2.8 on 2021-10-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('site', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='dbform',
            name='id',
        ),
        migrations.AlterField(
            model_name='dbform',
            name='First_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
