# Generated by Django 3.2.8 on 2021-10-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_course', '0004_inhritance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inhritance',
            new_name='inheritance',
        ),
    ]
